# SOURCE: https://github.com/hashicorp/tfc-workflows-github/blob/main/workflow-templates/terraform-cloud.speculative-run.workflow.yml
# SEE ALSO:
# https://developer.hashicorp.com/terraform/internals/json-format
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: Testing
on:
  # Allow manual runs
  workflow_dispatch:
  
# Shared Environment Variables
# IMPORTANT: Some actions read these values implicitly i.e. they may not appear in below code.
# env:

# Save computation resources by cancelling any in-progress runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout git ref"
        uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout 

      - name: Load example Terraform Plan from file
        shell: pwsh
        run: |
          $json = Get-Content '.github/workflows/Example TF Plan.json' | ConvertFrom-Json
          echo "Address: $($json[0].address)"

      
